### ISSUE TITLE
models are not included from subpackages

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [svenkubiak/mangooio-hibernate-extension#4]
when configured like this
```
hibernate:
        models     : com.build.pkg.models
```

Only Classes from com.build.pkg.models package are picked up and not com.build.pkg.models.subpackage

is it by design?

**Comment by MarkVink** [comment]
I experienced the same behaviour when locating my enums in a sub package, and also limitations when I wanted to use models from shared projects. I tried looking into changing the code of this extension, but ended up by just using my own hibernate.cfg.xml file.

**Comment by svenkubiak** [comment]
Sorry, for the late reply.

I have just release version 3.2.0 with a new classpath scanner. Should be on maven central soon. With the new scanner at hand you should be able to scann sub packages as well.


Please re-open if the problem still exisits.
